# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginInpromise():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginInpromise(self):
    # Test name: Login Inpromise
    # Step # | name | target | value
    # 1 | open | /login | 
    self.driver.get("https://inpromise.pnep.co.id/login")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | tester@kctgroup.co.id
    self.driver.find_element(By.ID, "email").send_keys("tester@kctgroup.co.id")
    # 5 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 6 | type | id=password | 123456789
    self.driver.find_element(By.ID, "password").send_keys("123456789")
    # 7 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 8 | click | css=.backgroundSlideshowLayer:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".backgroundSlideshowLayer:nth-child(2)").click()
    # 9 | close |  | 
    self.driver.close()
  
